from eating.model import (
    Restaurant,
    User,
    Rating,
    Fountain,
    FountainRating,
    Cuisine,
    connect_to_db,
    db,
)
from run import app
from werkzeug.security import generate_password_hash
import os

os.system("source config.sh")
os.system("dropdb eating_disneyland")
os.system("createdb eating_disneyland")

app.app_context().push()

db.create_all()
print("Tables created...")

cuisines = [
    "Breakfast",
    "American",
    "Southern",
    "Mexican",
    "Italian",
    "Dessert",
    "Snacks",
    "Coffee",
    "Alcohol",
    "Intergalactic",
]

users = [
    {
        "username": "tinytim",
        "password": generate_password_hash(
            os.environ["USER_PW"], method="pbkdf2:sha256", salt_length=8
        ),
        "email": "t@t.com",
        "age": 40,
        "zipcode": 92692,
    },
    {
        "username": "myquizowski",
        "password": generate_password_hash(
            os.environ["USER_PW"], method="pbkdf2:sha256", salt_length=8
        ),
        "email": "mw@mw.com",
        "age": 18,
        "zipcode": 84045,
    },
    {
        "username": "larrythelarry",
        "password": generate_password_hash(
            os.environ["USER_PW"], method="pbkdf2:sha256", salt_length=8
        ),
        "email": "l@l.com",
        "age": 65,
        "zipcode": 92692,
    },
]

restaurants = [
    {
        "name": "Carnation Cafe",
        "land": "Main Street",
        "expense": "$$$",
        "image_url": "https://static.wikia.nocookie.net/disney/images/6/65/Carnation_Cafe_2012.png",
        "description": "Dine on classic American comfort food, including some of Walt’s favorite dishes, at this Main Street, U.S.A. institution.",
        "full_service": True,
        "x_coord": 33.811067,
        "y_coord": -117.919103,
    },
    {
        "name": "Gibson Girl Ice Cream Parlor",
        "land": "Main Street",
        "expense": "$",
        "image_url": "https://farm9.static.flickr.com/8421/7763878548_b4dca6cb9b_b.jpg",
        "description": "Disneyland Main Street's nostalgic ice cream parlor & sweet shop with an elaborate old-timey Americana theme.",
        "full_service": False,
        "x_coord": 33.811165,
        "y_coord": -117.919086,
    },
    {
        "name": "Market House",
        "land": "Main Street",
        "expense": "$",
        "image_url": "https://lh3.googleusercontent.com/p/AF1QipP0o24z8tLQuz63ppjHGB0zQoKiU6Tj9_5BUAtx=s680-w680-h510",
        "description": "Disneyland's very own Starbucks.",
        "full_service": False,
        "x_coord": 33.810929374836455,
        "y_coord": -117.91888406625188,
    },
    {
        "name": "Refreshment Corner",
        "land": "Main Street",
        "expense": "$",
        "image_url": "https://allears.net/wp-content/uploads/archive/dining/images/dining_location_image_1970.jpg",
        "description": "Casual Disney stop for quick American fare including hot dogs, pretzels, and desserts.",
        "full_service": False,
        "x_coord": 33.811440,
        "y_coord": -117.919081,
    },
    {
        "name": "Plaza Inn",
        "land": "Main Street",
        "expense": "$$",
        "image_url": "https://www.disneytouristblog.com/wp-content/uploads/2012/03/DSC_7449.jpg",
        "description": "Quick-serve spot in Disneyland featuring a character breakfast buffet, as well as pay-per-item lunch and dinner buffets with themed dishes.",
        "full_service": False,
        "x_coord": 33.8116963939521,
        "y_coord": -117.91851581766903,
    },
    {
        "name": "Little Red Wagon",
        "land": "Main Street",
        "expense": "$",
        "image_url": "https://www.disneytouristblog.com/wp-content/uploads/2014/07/little-red-wagon-disneyland-121.jpg",
        "description": "Counter-service cart serving hand-dipped corn dogs.",
        "full_service": False,
        "x_coord": 33.81148556711443,
        "y_coord": -117.9186905116349,
    },
    {
        "name": "Jolly Holiday Cafe",
        "land": "Main Street",
        "expense": "$$",
        "image_url": "https://www.disneyfoodblog.com/wp-content/uploads/2021/08/2021-disneyland-jolly-holiday-bakery-cafe.jpg",
        "description": "Mary Poppins-inspired cafe serving breakfast and lunch options and desserts.",
        "full_service": False,
        "x_coord": 33.81168285912394,
        "y_coord": -117.9193818473908,
    },
    {
        "name": "Rancho Del Zocalo",
        "land": "Frontierland",
        "expense": "$$",
        "image_url": "https://live.staticflickr.com/7011/6678915119_90248b4eb4_b.jpg",
        "description": "Mexican eatery offering a variety of Mexican dishes in a lively setting with lots of shaded, outdoor seating.",
        "full_service": False,
        "x_coord": 33.81245859568607,
        "y_coord": -117.9199964482139,
    },
    {
        "name": "Edelweiss Snacks",
        "land": "Fantasyland",
        "expense": "$",
        "image_url": "https://static.wikia.nocookie.net/disney/images/4/48/EdelweissSnacksExterior.jpg",
        "description": "Visit this alpine chalet where you’ll be happy to meet turkey legs, chimichangas and buttered corn on the cob. Then, chill out in the shadow of the Matterhorn with a fountain drink or frozen beverage in blue raspberry, cherry or apple.",
        "full_service": False,
        "x_coord": 33.81374305708073,
        "y_coord": -117.91774430413204,
    },
    {
        "name": "Red Rose Taverne",
        "land": "Fantasyland",
        "expense": "$$$",
        "image_url": "https://www.disneytouristblog.com/wp-content/uploads/2017/03/red-rose-taverne-beauty-beast-restaurant-disneyland-048.jpg",
        "description": "Fantasy-story themed cafe with indoor and outdoor seating featuring American eats inspired from Disney films.",
        "full_service": False,
        "x_coord": 33.81346065509974,
        "y_coord": 117.9194651550013,
    },
    {
        "name": "Pizza Planet",
        "land": "Tomorrowland",
        "expense": "$$",
        "image_url": "https://www.disneyfoodblog.com/wp-content/uploads/2021/07/2021-dl-disneyland-pizza-planet-atmosphere.jpg",
        "description": "Quick-service pizza, pasta, & salad in a colorful, futuristic setting.",
        "full_service": False,
        "x_coord": 33.811728031793685,
        "y_coord": -117.91691154585381,
    },
    {
        "name": "Galactic Grill",
        "land": "Tomorrowland",
        "expense": "$",
        "image_url": "https://i0.wp.com/attractioninsight.com/wp-content/uploads/2022/08/galactic-grill-dlr.jpg?fit=2400%2C1600&quality=100&strip=all&ssl=1",
        "description": "Basic American eats with covered outdoor seating and viewing access to the Jedi Training Academy show.",
        "full_service": False,
        "x_coord": 33.8123815226415,
        "y_coord": -117.91715260949891,
    },
    {
        "name": "Troubadour Tavern",
        "land": "Fantasyland",
        "expense": "$",
        "image_url": "https://www.disneyfoodblog.com/wp-content/uploads/2015/07/TroubadourTavern_15_013.jpg",
        "description": "Sounter-serve snack shack with a Middle-Ages motif & menu with light fare.",
        "full_service": False,
        "x_coord": 33.8144856242707,
        "y_coord": -117.91875940912425,
    },
    {
        "name": "Daisy's Diner",
        "land": "Toontown",
        "expense": "$$",
        "image_url": "https://i1.wp.com/diningatdisney.com/wp-content/uploads/2014/06/DSC01131-d@d.jpg?ssl=1",
        "description": "Daisy Duck-themed walk-up window in Toontown serving pizza, salad, and soda",
        "full_service": False,
        "x_coord": 33.81551618186138,
        "y_coord": -117.91871838555176,
    },
    {
        "name": "Pluto's Doghouse",
        "land": "Toontown",
        "expense": "$",
        "image_url": "https://farm3.static.flickr.com/2823/9874579363_c1c487a0d9_b.jpg",
        "description": "Walk-up window serving picnic baskets with a variety of options, geared toward kids.",
        "full_service": False,
        "x_coord": 33.81554960890238,
        "y_coord": -117.91871033892531,
    },
    {
        "name": "Clarabelle's",
        "land": "Toontown",
        "expense": "$",
        "image_url": "https://i.ytimg.com/vi/op2ovjXYyTo/maxresdefault.jpg",
        "description": "Toontown's own hand-scooped ice cream from a walk-up window.",
        "full_service": False,
        "x_coord": 33.81557802187698,
        "y_coord": -117.91868821070254,
    },
    {
        "name": "Milk Stand",
        "land": "Galaxy's Edge",
        "expense": "$$",
        "image_url": "https://static.wikia.nocookie.net/starwars/images/3/3d/Milk-Stand.png",
        "description": "Cool down with an icy cup of blue or green milk inspired by the Star Wars universe.",
        "full_service": False,
        "x_coord": 33.814428886234296,
        "y_coord": -117.92069637808706,
    },
    {
        "name": "Olga's Cantina",
        "land": "Galaxy's Edge",
        "expense": "$$$",
        "image_url": "https://blogmickey.com/wp-content/uploads/2019/06/ogas-cantina-review-interior-1.jpg",
        "description": "Star Wars-themed bar featuring quirky cocktails (with and without alcohol), snacks, and a droid for a DJ.",
        "full_service": True,
        "x_coord": 33.8147258031444,
        "y_coord": -117.920964585531,
    },
    {
        "name": "Docking Bay 7 Food and Cargo",
        "land": "Galaxy's Edge",
        "expense": "$$",
        "image_url": "https://www.disneytouristblog.com/wp-content/uploads/2019/07/docking-bay-7-food-cargo-star-wars-galaxys-edge-disney-counter-service-restaurant-234.jpg",
        "description": "Spacious hangar with a generic Star Wars spaceport theme serving informal international eats such as noodles and ribs.",
        "full_service": False,
        "x_coord": 33.81469267859092,
        "y_coord": -117.92147272989884,
    },
    {
        "name": "Ronto Roasters",
        "land": "Galaxy's Edge",
        "expense": "$$",
        "image_url": "https://ziggyknowsdisney.com/wp-content/uploads/2019/10/ronto-roasters-galaxys-edge-11-pod-racing-engine-800x533.jpg",
        "description": "Counter-serve option for intergalactic pork or vegetarian wraps.",
        "full_service": False,
        "x_coord": 33.814462613156586,
        "y_coord": -117.92153869443413,
    },
    {
        "name": "Hungry Bear",
        "land": "Critter Country",
        "expense": "$",
        "image_url": "https://farm4.static.flickr.com/3821/12143478353_43313610fa_b.jpg",
        "description": "Rustic, counter-serve option featuring traditional American fare with lots of covered, outdoor seating overlooking the Rivers of America.",
        "full_service": False,
        "x_coord": 33.812590935972715,
        "y_coord": -117.92260721018377,
    },
    {
        "name": "Harbour Galley",
        "land": "Critter Country",
        "expense": "$$",
        "image_url": "https://blog-cdn.touringplans.com/blog/wp-content/uploads/2021/12/IMG_5040.jpg",
        "description": "Drop anchor along the waterfront and stop by this swell seafood shanty for a quick meal that’ll set your taste buds afloat.",
        "full_service": False,
        "x_coord": 33.812041180621804,
        "y_coord": -117.9219757109676,
    },
    {
        "name": "Mint Julep Bar",
        "land": "New Orleans Square",
        "expense": "$$",
        "image_url": "https://www.disneyfoodblog.com/wp-content/uploads/2013/07/Mint-Julep-Bar.jpg",
        "description": "Old-timey, New Orleans-themed walk-up window for nonalcoholic cocktails and espresso drinks, as well as beignets.",
        "full_service": False,
        "x_coord": 33.811182398373205,
        "y_coord": -117.92166376575899,
    },
    {
        "name": "French Market Restaurant",
        "land": "New Orlean's Square",
        "expense": "$$",
        "image_url": "https://www.disneyland4ever.com/uploads/2/4/8/5/24855797/719057659.jpg",
        "description": "New Orleans-themed eatery with Southern fare, counter service, and a covered, garden patio.",
        "full_service": False,
        "x_coord": 33.81125204155685,
        "y_coord": -117.92162085041623,
    },
    {
        "name": "Cafe Orleans",
        "land": "New Orleans Square",
        "expense": "$$$",
        "image_url": "https://www.disneytouristblog.com/wp-content/uploads/2014/01/disneyland-christmas-2013-069.jpg",
        "description": "Classic restaurant featuring Cajun & Creole specialties in casual surrounds with a patio.",
        "full_service": True,
        "x_coord": 33.811243684377416,
        "y_coord": -117.92120041416223,
    },
    {
        "name": "Blue Bayou Restaurant",
        "land": "New Orleans Square",
        "expense": "$$$$",
        "image_url": "https://i.pinimg.com/originals/48/2f/54/482f54c4b7e39c2f00314efb98daf13f.jpg",
        "description": "Evocative Cajun-style restaurant set inside the Pirates of the Caribbean ride with an outdoor, nighttime bayou ambience.",
        "full_service": True,
        "x_coord": 33.811113869426435,
        "y_coord": -117.9210944669072,
    },
    {
        "name": "Royal Street Veranda",
        "land": "New Orlean's Square",
        "expense": "$",
        "image_url": "https://www.ocregister.com/wp-content/uploads/migration/o0k/o0k397-b88517818z.120160106161000000gn7ctph7.20.jpg?w=978",
        "description": "Counter-service window serving Cajun-style soups in bread bowls.",
        "full_service": False,
        "x_coord": 33.811242012942394,
        "y_coord": -117.92095096871431,
    },
    {
        "name": "River Belle Terrace",
        "land": "Frontierland",
        "expense": "$$$",
        "image_url": "https://www.wdwinfo.com/wp-content/uploads/2018/12/IMG_6009.jpg",
        "description": "Antebellum-style eatery with a riverfront terrace for Southern dining",
        "full_service": True,
        "x_coord": 33.81149662796846,
        "y_coord": -117.92051108644743,
    },
    {
        "name": "Bengal Barbecue",
        "land": "Adventureland",
        "expense": "$$",
        "image_url": "https://static.wikia.nocookie.net/junglecruise/images/d/dc/9877129093_fe24e00648_b.jpg",
        "description": "Counter-serve spot featuring grilled meat & veggie skewers and other casual, jungle eats.",
        "full_service": False,
        "x_coord": 33.81154732802444,
        "y_coord": -117.92031126189028,
    },
    {
        "name": "Stage Door Cafe",
        "land": "Frontierland",
        "expense": "$",
        "image_url": "https://www.ocregister.com/wp-content/uploads/migration/o0k/o0k3m7-b88517821z.120160106161829000g84crc77.20.jpg?w=1024",
        "description": "Fast-food outpost serving hand-dipped corn dogs, chicken tenders, and funnel cakes.",
        "full_service": False,
        "x_coord": 33.81189888473691,
        "y_coord": -117.9203206496091,
    },
    {
        "name": "Golden Horseshoe",
        "land": "Frontierland",
        "expense": "$",
        "image_url": "https://www.disneytouristblog.com/wp-content/uploads/2015/04/golden-horseshoe-disneyland-night.jpg",
        "description": "Quick-serve saloon serving fish 'n' chips, ice cream, and chicken strips with live Western music shows.",
        "full_service": False,
        "x_coord": 33.812048755541824,
        "y_coord": -117.9202844397871,
    },
    {
        "name": "Turkey Leg Cart",
        "land": "Frontierland",
        "expense": "$$",
        "image_url": "https://www.disneyfoodblog.com/wp-content/uploads/2014/03/Frontierland-Turkey-leg-Cart-2.jpg",
        "description": "Cart offering Disneyland's classic, gigantic, smoked turkey legs.",
        "full_service": False,
        "x_coord": 33.812423735113434,
        "y_coord": -117.92057041285449,
    },
    {
        "name": "Maurice's Treats",
        "land": "Fantasyland",
        "expense": "$",
        "image_url": "https://diningatdisney.com/wp-content/uploads/2013/07/Maurices-Treats.jpg",
        "description": "Beauty and the Beast themed wagon offering savory and sweet pastries and fruit-flavored frozen drinks.",
        "full_service": False,
        "x_coord": 33.81250160079871,
        "y_coord": -117.91931709893191,
    },
]

fountains = [
    {
        "name": "Red Rose Tavern Fountain",
        "land": "Fantasyland",
        "image_url": "red_rose.png",
        "description": "In the olden times I was left to myself for most of the day, but since the contruction of Galaxy's Edge I can't begin to tell you how many humans must exist on this planet. It might even be in the millions. Come say hi so I can add you to the human tally.",
        "x_coord": 33.813555095191816,
        "y_coord": -117.91969266601622,
    },
    {
        "name": "River Belle Terrace Fountain",
        "land": "Frontierland",
        "image_url": "river_belle.png",
        "description": "Elegantly aged, I sit in front of the River Belle Terrace seating area, facing Pirate Island. Without much relief from the sun, my water isn't often very cool, but grab yourself a cup of ice and come fill up!",
        "x_coord": 33.81179993283393,
        "y_coord": -117.92053414788177,
    },
    {
        "name": "Small World Fountain",
        "land": "Fantasyland",
        "image_url": "small_world.png",
        "description": "Unassiming and practical, I enjoy occasional peace and quiet simply because of how few people know I exist.",
        "x_coord": 33.814428366540696,
        "y_coord": -117.91849157457128,
    },
    {
        "name": "Parade Route Fountain",
        "land": "Fantasyland",
        "image_url": "alice.png",
        "description": "You probably don't recognize me, and yet you've probably drunk from me before! I serve all passerby lost between Main Stree, Tomorrowland, and Fantasyland. Come hang out with me and have a front-row seat to our lovely parades.",
        "x_coord": 33.81285552883391,
        "y_coord": -117.91843914882486,
    },
    {
        "name": "Astro Blasters Fountain",
        "land": "Tomorrowland",
        "image_url": "astro_blasters.png",
        "description": "Never seen me before? Doesn't surprise me. They built me in a corner of a nook, and frankly I'm generally okay with that. Except that my cutout of the park has begun to serve as a resting place for larger species of humans while their families stand in line. I stand all the time; it must be how I keep my slim figure. Come get an autograph sometime!",
        "x_coord": 33.812256429837916,
        "y_coord": -117.91750832020742,
    },
    {
        "name": "Autopia Fountain",
        "land": "Tomorrowland",
        "image_url": "autopia.png",
        "description": "Strollers...so many strollers! I can be seen from afar, though getting to me is like navigating a stroller minefield. Frankly, I like them. I like the moms and kids who hang out here. I'm an aspiring mother too, you know? I'm young and sleek and someday I hope one of the dashing fountains around here figures out how to move over here. Maybe we can have little baby fountains too; imagine how many water bottles we could fill! \nSorry, I don't mean to ramble. I'd love to meet you soon so come say hi (and feel free to bring a handsome fountain along with you if you can).",
        "x_coord": 33.812474675752576,
        "y_coord": -117.91680448439969,
    },
    {
        "name": "Black Spire Outpost Fountain",
        "land": "Galaxy's Edge",
        "image_url": "ge_droid.png",
        "description": "Beep boop beebop- oh wait, you’re human! We’ve been getting lots of humans these days in Black Spire Outpost, and what I have realized is that they all need something to drink! Alas, most of them seem to prefer blue milk from the Milk Stand around the corner.\nBut I stand here proudly for all those who stand against spending antiquated republic credits, or drinking sugar. My water is the finest in Batuu, because the First Order regulates my supply. That other fountain at the edge of the marketplace is run by the resistance and local merchants, and I trust them as far as I can throw them.\nBut if history has taught me and my nearby droids anything, it’s that they’ll pull out a narrow and complete victory over my First Order right at the end when things seem most bleak.\nWhoever you side with, come keep me company sometime! I speak human, droid, and jawa, and my water is purified 12 times with kyber filters.",
        "x_coord": 33.81430278429254,
        "y_coord": -117.92086429755778,
    },
    {
        "name": "Resistance Fountain",
        "land": "Galaxy's Edge",
        "image_url": "ge_south.png",
        "description": "I am pleased to serve you. Please don't stay too long. I do not mingle, for my function is simply to dispense liquid life to humanoids. Come back soon if you wish. My emotional processors don't concern themselves with trivialities like relationships and affection, so I'll be fine.",
        "x_coord": 33.8143674858366,
        "y_coord": -117.92194055669907,
    },
    {
        "name": "Hungry Bear Cafe Fountain",
        "land": "Critter Country",
        "image_url": "hungry_bear.png",
        "description": "I'd have a really great view of the Rivers of America if there weren't always people walking by. But sometimes, it's quite peaceful around here. I live on the ground level of the Hungry Bear patio, where it's always shaded. Good luck finding a place to sit on a hot day, and good luck staying warm here on a cold day. Those are my struggles anyway. Please don't feed the ducks.",
        "x_coord": 33.81268313337089,
        "y_coord": -117.9225012725457,
    },
    {
        "name": "West of Big Thunder Mountain Fountain",
        "land": "Frontierland",
        "image_url": "big_thunder_west.png",
        "description": "Howdy partners! I seen y’all come around here quite a bit without even knowin’ it. This little corner of the park has always been a spot for folks to stop for a few seconds to reset. I see them look at the map, figure out where they are, figure out where they wanna go, discuss their next meal, split up for a few, meet up after a ride, and sometimes they casually get into the long Fastpass line for Big Thunder by mistake, only to be turned away at the front.\nAnd just look at the scenery - what a place I get to live! Plus they got turkey legs, elotes, churros, popcorn, pretzels, chimichangas, and plenty of other good-smellin’ treats nearby.\nAnd ever since that new Galaxy Star place opened up, boy the traffic ‘round here has gone up. I love it! You won’t regret grabbing’ a sip from me on your way to or from this charming Frontierland.",
        "x_coord": 33.81285885777622,
        "y_coord": -117.92084117296432,
    },
    {
        "name": "Indiana Jones Entrance Fountain",
        "land": "Adventureland",
        "image_url": "indy_inside.png",
        "description": "It’s great that you found me, but don’t linger! Many dangers await those who don’t make haste to leave this temple... Come to get a drink, have you? Be careful how you choose - the ancient architects made sure that the writing was on the wall. If you must, take a sip, then run to catch up to your party! The line is barely halfway done here. Unless you possess the sacred relic they call a Fastpass.",
        "x_coord": 33.81109331837419,
        "y_coord": -117.92058063828422,
    },
    {
        "name": "Indiana Jones Exit Fountain",
        "land": "Adventureland",
        "image_url": "indy_inside2.png",
        "description": "So you made it past the boulder and the snakes and the fire and all the other robotic mechanisms that are designed to never actually get anyone, eh? Congratulations. Have a sip - most people pass me right by. After all, pretending to go on an adventure ride full of booby-traps makes you forget about your hunger and thirst for a time.",
        "x_coord": 33.81082687521391,
        "y_coord": -117.92082233051566,
    },
    {
        "name": "Tom Sawyer Island East Fountain",
        "land": "Frontierland",
        "image_url": "island_bottles.png",
        "description": "Admittedly, I don't serve as a normal drinking fountain per se, but I can surely fill up your receptacles! Plus I have this old, rusty water pump next to me that doesn't work! Next time you go to Tom Sawyer Island, come say hi to me before you leave. Seriously, I would really appreciate more people coming to say hi. I don't think you realize how lonely it is out here marooned on this island with an identity crisis.",
        "x_coord": 33.81217403989266,
        "y_coord": -117.9211124488421,
    },
    {
        "name": "Jungle Cruise Entrance Fountain",
        "land": "Adventureland",
        "image_url": "j_cruise.png",
        "description": "I live outside the Jungle Cruise, almost sandwiched between Indiana Jones. This might be one of the busiest spots in the entire park, but I dispense less water than some other fountains. I attribute it to the fact that this is one of the busiest spots in the entire park. Like, all the time. 8am? Packed. 10pm? packed. Light outside? You might see me surrounded by a throng of oversize people scarfing down a $20 meat kebab. But if it's dark, you'll probably miss me altogether. I'm not bitter about how crowded it is, but I really don't like it and I feel a little bitter about it.",
        "x_coord": 33.81146344226622,
        "y_coord": -117.92012828223598,
    },
    {
        "name": "Outside Main Street Disney Gallery",
        "land": "Main Street",
        "image_url": "main_2spigot.jpeg",
        "description": "Well, well, well. You'll look at me here on this web page but you don't bat an eye when you're standing here in front of me. I suppose it could be because I'm not noticeable enough because of my small stature. But that's just my mopiness talking; the truth is most likely that anyone passing by me is either in a rush to get to a ride, or in a rush to get to their ride. That was a pretty good line right? For more clever thoughts, come hang out with me sometime! Or go off to try and beat the line to the Resistance ride or the Space land ride or the Boulder ride or whatever you need to do with your day at Disneyland.",
        "x_coord": 33.8101924348343,
        "y_coord": -117.91868648420481,
    },
    {
        "name": "West of The Mad Hatter",
        "land": "Main Street",
        "image_url": "main_3spigot.jpeg",
        "description": "Welcome to the park! Most of you have taken a sip from me before. I'm easy to notice and easier to love, just like I already love all of you. Except for teenagers, but no one really loves teenagers and they are usually too cool for water anyway.\nAnyway, I just really love being here. What a lively atmosphere. You could always go drink from my western or southeastern counterparts, but once you're done with them, remember who quenched your thirst first.",
        "x_coord": 33.81041649323696,
        "y_coord": -117.91888918668134,
    },
    {
        "name": "East of the Fire Department",
        "land": "Main Street",
        "image_url": "main_nw.jpeg",
        "description": "I don't have much time to talk. People. People everywhere! So many people! AAAAAAAHHGGGG",
        "x_coord": 33.81041806041907,
        "y_coord": -117.9190672130465,
    },
    {
        "name": "Pirates of the Caribbean East Fountain",
        "land": "New Orleans Square",
        "image_url": "pirates_east.png",
        "description": "I may be overshadowed by my western counterpart, but I'm also overshadowed by the trees - and their shade chills my water just a wee bit more. To be fair, it doesn't really chill the water much. But the shade is nice. I wish I could go on this Pirate ride, but I dream.",
        "x_coord": 33.811384434770694,
        "y_coord": -117.92077021710217,
    },
    {
        "name": "Pirates of the Caribbean West Fountain",
        "land": "New Orleans Square",
        "image_url": "pirates_west.png",
        "description": "Which way will you go? Right or left? Most folks - being right-handed, believing in right-favoring superstitions, and I have to assume because they know they'll find me - choose to go right when entering Pirates. The regulars think they have it all figured out, and sometimes they visit my easterly brother instead. But in the end I know I'll see you again.\nOh and I should mention, by the time you finish your drink here your party will be up the hill quite a ways and the person behind you will be uncertain whether they should keep moving past you or wait. It's funny for me to watch, anyway.",
        "x_coord": 33.811379420471226,
        "y_coord": -117.92088354042427,
    },
    {
        "name": "Fresh-off Space Mountain Fountain",
        "land": "Tomorrowland",
        "image_url": "space_exit.jpeg",
        "description": "",
        "x_coord": 33.81107140981236,
        "y_coord": -117.91746235335155,
    },
    {
        "name": "After the Space Mountain Ride Photo Fountain",
        "land": "Tomorrowland",
        "image_url": "space_exit_2.jpeg",
        "description": "My life is something special. Here in this blue hallway outside Space Mountain, I get to serve oodles of people every minute. And the best part is, it’s always crazy blue like this! It almost gives you a headache. And the best part is, it’s super crowded with no obvious right way for the foot traffic to go, so it’s crazy all the time! And the best part is, people all over Tomorrowland come to use this restroom next to me, but since it’s a little out of the way and in a neon blue hallway which is crowded all the time, they lose a little patience with each other. Well anyway, come on by and grab a drink next time! Or skip me to ease traffic, I probably won’t recognize you anyway with this blinding blue light everywhere.",
        "x_coord": 33.8113087200458,
        "y_coord": -117.91759552791628,
    },
    {
        "name": "Star Tours Exit Fountain",
        "land": "Tomorrowland",
        "image_url": "star_tours_exit.png",
        "description": "Hello there. Back in the day, Star Tours was the only way for guests to experience Star Wars at Disneyland. Now, the best part of this ride is...me! I know I don't look like much, but you'll do well to fill your bottle or belly here after a quick trip around the galaxy because my hallway is air-conditioned all day long. That means my water is nice and chilly - unlike my outdoor counterparts.\nAnd please don't leave your 3D glasses on top of me, there's a bin down the way.",
        "x_coord": 33.81189793764987,
        "y_coord": -117.91776254628962,
    },
    {
        "name": "Space Mountain Line Fountain",
        "land": "Tomorrowland",
        "image_url": "space_line.png",
        "description": "Don't lose your spot while you take a sip - I sit right before the entrance into the corridor of eternal flatulent horror on your way to ride a roller coaster through outer space. Why humans do the things they do is simply beyond me; all I know is that you need water, and I'm here for you. It's your last chance. Unless you make it off the ride, and then there'll be some other chances.",
        "x_coord": 33.81130122807746,
        "y_coord": -117.91729173021712,
    },
    {
        "name": "Space Mountain Entrance Fountain",
        "land": "Tomorrowland",
        "image_url": "space_entrance.jpeg",
        "description": "I saw you looking at my friend over in the blue hallway and wanted to say hi as well! I’m right on the way up to the Space Mountain line entrance. I feel like I get to see some of the best action in the park in this little corridor: people running up to get a fastpass, people running past all the other humans nearby to get in line, people running back to get a fastpass our front (they moved the distribution machines), youngsters measuring up on the height requirement pole next to me, people walking into whatever seasonal movie is playing in the Captain Eo theater, old people getting tired walking up this long corridor and taking a break, children telling their old relatives to hurry up, people bummed that the ride broke down while they were in line. And when it’s slow, I can still just watch folks eating pizza on the patio across the way.\nIf I could go on any ride in the park, it would probably be Star Tours because people talk about it a lot as they walk by me.\nNext time you need a fastpass for Space Mountain, remember that if you see me, you’ve gone too far. But I’ll still give you some water!",
        "x_coord": 33.81145945770949,
        "y_coord": -117.91709654172291,
    },
    {
        "name": "Frontierland Rock Fountain",
        "land": "Frontierland",
        "image_url": "thunder.png",
        "description": "Handomest fountains in the park, you say? I'd argue if I could! Come grab a swig between shows at the Golden Horseshoe, between rides on Big Thunder, after a meal at Zocalo, or after stepping off Mark's Riverboat - there's plenty to do around here so I expect to see you return a couple times, even if only just to check me out.",
        "x_coord": 33.8122977996329,
        "y_coord": -117.92032523408298,
    },
    {
        "name": "Toontown Chip n Dale Fountain",
        "land": "Toontown",
        "image_url": "tt_double.png",
        "description": "Around Toontown we are known as Chip and Dale because we rescue folks from thirst on a daily basis. Yes it’s heroic, but it’s nice to start getting some recognition now.\nCartoon buildings must make people thirsty because Toontown has the highest number of fountains per triangular acre than any other Disneyland Land. I think.\nIf you look closely at the last photo you’ll see a preview of the next Fountain post, our solo friend we like to call Fat Cat because he’s our arch enemy. Even though he’s actually a pretty nice fountain and a decent alternative for when there’s 6 children gathered around us, all “drinking” water at the same time. Much water has been lost to the ground over the years because of uncoordinated children splashing and splashing and squirting their siblings.",
        "x_coord": 33.81538694827306,
        "y_coord": -117.91886781396086,
    },
    {
        "name": "Toontown Around-the-Corner Fountain",
        "land": "Toontown",
        "image_url": "tt_single.png",
        "description": "It really is an honor to be featured here, even if I did come after my nemeses around the corner. I like to think that without me, their fame would have dwindled long ago.\nI can’t complain about things over here in Toontown. There’s just so many kids all the time. It can get pretty frustrating actually, but otherwise it’s a good life. It would be better if there were no more children. But I count my blessings because around Disneyland the only thing worse than the children is the adults that come with them.",
        "x_coord": 33.81541311123864,
        "y_coord": -117.91888533689487,
    },
    {
        "name": "Toontown Grass Fountain",
        "land": "Toontown",
        "image_url": "tt_grass.png",
        "description": "As the most elegantly crafted and environmentally-friendly fountain in all the park, welcome to the corner of Toontown. I seriously can't get over myself - just look! You'd think I was just a couple patches of grass until you got up close! But actually, I think people must be thinking that, because I don't get a lot of visitors. It could also have to do with the excessive heat coming from this corner - partially from the reflective paint throwing the sunshine all around, but mostly because I'm just that good-looking. My water, however, is a smidge warm. And your kids might burn their fingers pushing the button. It's lonely at the top, but it's a sacrifice I'm willing to make. ",
        "x_coord": 33.81543234649819,
        "y_coord": -117.91936501170048,
    },
    {
        "name": "Plaza Inn Bathroom Fountain",
        "land": "Main Street",
        "image_url": "plaza_br.jpeg",
        "description": "Thanks for coming back to Main Street! I’m over closer to the Fire Department, and all the people trying to find a drink near the bathroom have to come over to me across the street. Plus, during the holidays I give drinks to all the bored family members who are waiting for others to take pictures with the Mickey Pumpkin or the giant Christmas Tree. Some look down on my rust stains, but to me they’re just battle scars. From the happiest battles on earth! Come for a sip on your way out of the park next time!",
        "x_coord": 33.81191017983494,
        "y_coord": -117.91830964389017,
    },
    {
        "name": "Plaza Pavilion White Fountain",
        "land": "Main Street",
        "image_url": "plaza_pavilion.jpeg",
        "description": "My elegance stands apart from all else - except for gigantic crowds around here basically all the time. That may be why you haven't spotted me. If it's parade time, find another fountain for everyone's sake. But by day, come and find me! I make for great photo opportunities. ",
        "x_coord": 33.81186382318189,
        "y_coord": -117.91929370519357,
    },
    {
        "name": "In the Fruit Cart Alley",
        "land": "Main Street",
        "image_url": "main_alley.jpeg",
        "description": "Welcome to my adorable alley. I am so blessed to be here. Cast members come in and out, folks visit their lockers to grab goodies, and of course the occasional regular strolls over seeking a moment of solitude. I just adore my private life here on this beautiful brick wall, and from my perspective the view is also outstanding! I get to look at this flower tree and all the colorful fruits! We have the freshest fruit carts this side of Adventureland.\nI sincerely hope you can come visit soon - I offer the most tranquil water fountain experience in the park, and afterwards you can enjoy my quaint alleyway before heading off to Space Land or Toon City or wherever your heart desires!",
        "x_coord": 33.811003404192626,
        "y_coord": -117.91870759418997,
    },
    {
        "name": "Fantasy Faire Gifts Fountains",
        "land": "Fantasyland",
        "image_url": "fantasy_faire.jpeg",
        "description": "You probably don’t see me often. Even I forgot I was over here! Every 15 minutes I get to listen to the Small World clock procession so I always know what time it is, but I sleep through most of them by now. But whenever someone forgets to buy a drink with their pretzels or popcorn nearby I get to see some serious action. And I don’t want to brag, but you see how clean I am? Probably the cleanest fountain in the park. Someday, I hope to make it to Toontown. If you feel like a drink and happen to be coming out of Toontown, consider the fountains by Troubador Tavern so I can keep sleeping. Thanks.",
        "x_coord": 33.814259750170635,
        "y_coord": -117.91827195384943,
    },
    {
        "name": "Cafe Orleans Fountain",
        "land": "New Orleans Square",
        "image_url": "cafe_orleans.jpeg",
        "description": "You found me! I’m hidden here in plain sight because I blend into the railing and lampposts, so most people walk right by, but just look at what you’re missing!\nAlthough my main body keeps with the design of my other New Orleans Square fountains, I dare you to find another fountain like my little stand-alone stump! As far as I know, it’s one-of-a-kind in the park.\nCome grab a drink as soon as you can and have a chat with all the folks on the Cafe Orleans patio. They love it when people talk to them over the railing while they’re trying to eat!",
        "x_coord": 33.81126946928877,
        "y_coord": -117.92113006069728,
    },
    {
        "name": "West of the Park Entrance",
        "land": "Main Street",
        "image_url": "outside_entrance.jpeg",
        "description": "Psst. Hey you. Yeah, you...come here. Listen...wanna grab a drink? I'm your last chance before you go inside the park. Unless you go across the way to the one outside of California Adventure. But once you're inside, that's it. I have it on good authority that there is no water in the parks, so chance it if you will. But by the time you leave, you'll be in such a hurry to beat everyone else to stand in the tram line that you'll pass me right by, parched or not.\nDon't say I didn't warn you...",
        "x_coord": 33.80972792358568,
        "y_coord": -117.91958240170382,
    },
    {
        "name": "New Orleans Back-Alley Fountain",
        "land": "New Orleans Square",
        "image_url": "orleans_alley.jpeg",
        "description": "You might think it’s a peaceful life way back here, but you’d be super wrong because it’s crowded and loud basically all the time. I don’t know why it’s so crowded. I’m in the back alley by the caricature artist - what is everyone doing back here?\nI know that I’m very beautiful so people might want to come spectate. Sure, attention is great, but sometimes a fountain just needs a little peace and quiet.\nAnd if all the normal people weren’t enough, there are pirates! Just random pirates who apparently live here and just want to play music every few hours. Really loud music. I could also do without hearing every men’s toilet flush behind this brick wall. But I need to be grateful, sometimes the music and the smiling people are quite nice.\nI often dream of moving to Fantasyland... I’ll bet there’s nothing but peace and quiet there!",
        "x_coord": 33.8110131995114,
        "y_coord": -117.9216045738334,
    },
    {
        "name": "Tom Sawyer's First Fountain",
        "land": "Frontierland",
        "image_url": "tsawyer_entrance.jpeg",
        "description": "Welcome to the island! I greet you all as you step off the transport raft to this island first claimed by Tom Sawyer, and then by pirates. What a great life it is, too. Never too crowded, always a nice temperature, and I can hear the screems from Splash Mountain all day and night. Between the kids playing hide & seek and the parents getting frustrated at how good their kids are at hide & seek, it's a real hoot to camp out here for a while.\nAnd don't tell them I said so, but every day I swear that one of our guests is going to capsize that raft. I've only seen it once or twice though, so you're probably good to have that 7th churro.",
        "x_coord": 33.812029453897,
        "y_coord": -117.92131529211416,
    },
    {
        "name": "Toontown Entrance Fountain",
        "land": "Toontown",
        "image_url": "tt_entrance.jpeg",
        "description": "Welcome to Toontown, the silliest place to live in the park! Kids and adults find some common ground in Toontown, and I love it. There’s so much going on over here - why just the other day I heard about a fountain that makes silly noises. And I can see a lamppost twisted in a knot in the distance, and some of these houses are slanted! And don’t even get me started on the September-December season - they go all out!!\nRight in front of me is the most popular attraction here, the Roger Rabbit Car-Toon Spin. Maybe one day I’ll go on it, but I just can’t figure out how they fit an hour-long line into that little building.\nWell anyway, if you ever wanna hang, my spot is the calmest in Toontown. 3.5 other brothers and sisters are placed throughout this land, and word travels through the pipeline that they are busy all day long. And they are out in the brutal sunshine. There’s always plenty of shade and seating near me, so come and say hello soontown!",
        "x_coord": 33.81499993991573,
        "y_coord": -117.91804791150751,
    },
    {
        "name": "Goofy Water Fountain",
        "land": "Toontown",
        "image_url": "goofy.jpeg",
        "description": "I am downright honored to be the April Fool’s Day feature on this page. Though, if you ask me, these Disney folks have let this in-park April Fool’s joke go on for way too long! I haven’t seen a visitor in weeks! They’re always doing something festive.\nI’m happy to be the silliest water fountain in the park, and if you swipe right, you can hear the best part - though it’s difficult fitting all those characters into my plumbing system. At nighttime they tend to argue down there and it gets bothersome when I want to sleep.\nMany people come just to hear the noise, but next time you come around, take a real drink as well. Maybe it’s all the silly noises vibrating the water in the pipes, but my water is the best tasting in the whole park! And that’s no joke!",
        "x_coord": 33.81542979231428,
        "y_coord": -117.91873174132668,
    },
]

os.system("source config.sh")

for cuisine in cuisines:
    new_cuisine = Cuisine(name=cuisine)
    db.session.add(new_cuisine)

print("Cuisine table done")

for user in users:
    new_user = User(
        username=user["username"],
        password=user["password"],
        email=user["email"],
        age=user["age"],
        zipcode=user["zipcode"],
    )
    db.session.add(new_user)

print("User table done")

for restaurant in restaurants:
    new_restaurant = Restaurant(
        name=restaurant["name"],
        land=restaurant["land"],
        expense=restaurant["expense"],
        image_url=restaurant["image_url"],
        description=restaurant["description"],
        full_service=restaurant["full_service"],
        x_coord=restaurant["x_coord"],
        y_coord=restaurant["y_coord"],
    )
    db.session.add(new_restaurant)

print("Restaurant table done")

for fountain in fountains:
    new_fountain = Fountain(
        name=fountain["name"],
        land=fountain["land"],
        image_url=fountain["image_url"],
        description=fountain["description"],
        x_coord=fountain["x_coord"],
        y_coord=fountain["y_coord"],
    )
    db.session.add(new_fountain)

db.session.commit()

cc_rating = Rating(
    star_rating=4,
    review="Lively location on Main Street.",
    restaurant=Restaurant.query.filter_by(name="Carnation Cafe").first(),
    user=db.session.get(User, 1),
)
es_rating = Rating(
    star_rating=5,
    review="I love to come here for an authentic Swiss chimichanga.",
    restaurant=Restaurant.query.filter_by(name="Edelweiss Snacks").first(),
    user=db.session.get(User, 2),
)
hg_rating = Rating(
    star_rating=5,
    review="Great place for a snack, hidden in plain sight.",
    restaurant=Restaurant.query.filter_by(name="Harbour Galley").first(),
    user=db.session.get(User, 3),
)

rrtf_rating = FountainRating(
    star_rating=5,
    review="I love taking a sip near the Red Rose",
    user=db.session.get(User, 1),
    fountain=Fountain.query.filter_by(name="Red Rose Tavern Fountain").first(),
)
rbtf_rating = FountainRating(
    star_rating=4,
    review="It's truly warm water, but the locale is lovely.",
    user=db.session.get(User, 2),
    fountain=Fountain.query.filter_by(name="River Belle Terrace Fountain").first(),
)
swf_rating = FountainRating(
    star_rating=5,
    review="Sometimes I loiter here to absord the peace and quiet, and to have a constant water flow.",
    user=db.session.get(User, 3),
    fountain=Fountain.query.filter_by(name="Small World Fountain").first(),
)

db.session.add_all(
    [cc_rating, es_rating, hg_rating, rrtf_rating, rbtf_rating, swf_rating]
)
db.session.commit()

print("Ratings created")

print("Database successfully seeded.")
